# í…Œë§ˆ ì„¤ì •ì— ëŒ€í•œ ë¶€ë¶„ì…ë‹ˆë‹¤. ê¸°ë³¸ ì„¤ì •ì„ ìœ ì§€í•˜ì˜€ìŠµë‹ˆë‹¤.
theme: jekyll-theme-cayman
#remote_theme           : "mmistakes/minimal-mistakes"

title                    : "Android Studio App ê°œë°œê¸°ğŸ¤£"
name                     : "ê¹€ì˜ìš´"
description              : "java,"
url                      : "https://dnsdudrla97.github.io"
baseurl                  : "https://dnsdudrla97.github.io/app0/Android%20Develope%20Project%20by%20YOUNLSE.html"


