# í…Œë§ˆ ì„¤ì •ì— ëŒ€í•œ ë¶€ë¶„ì…ë‹ˆë‹¤. ê¸°ë³¸ ì„¤ì •ì„ ìœ ì§€í•˜ì˜€ìŠµë‹ˆë‹¤.
theme: jekyll-theme-cayman
#remote_theme           : "mmistakes/minimal-mistakes"

title                    : "Android Studio App ê°œë°œê¸°ğŸ¤£"
name                     : "ê¹€ì˜ìš´"
description              : "java,"
url                      : "https://dnsdudrla97.github.io/app0/Android%20Develope%20Project%20by%20YOUNLSE.html"
baseurl                  : "https://dnsdudrla97.github.io/app0/Android%20Develope%20Project%20by%20YOUNLSE.html"

teaser                   : "/assets/images/bio-photo-keyboard.jpg"
logo                     : # ìµœìƒë‹¨ ë©”ë‰´ ë°”ì— ì‚¬ì´íŠ¸ ë¡œê³  ë„£ê¸°


comments:
  provider               : # ë¸”ë¡œê·¸ ëŒ“ê¸€ ê¸°ëŠ¥ false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # ë¸”ë¡œê·¸ ëŒ“ê¸€ ê¸°ëŠ¥ https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)


